# Procesos globales por tipo de archivo
processes:
  audio:
    target_table: audios_procesados
    process_steps:
      - voice_detection
      - language_identification
      - speech_to_text
      - speaker_hunting
      - speaker_identification
      - event_detection
      - sentiment_analysis

  video:
    target_table: videos_procesados
    process_steps:
      - audio_extraction
      - thumbnail_extraction
      - metadata_extraction
      - face_detection
      - facial_composite_extraction
      - race_recognition
      - face_matching
      - object_detection
      - ocr
      - location_recognition

  image:
    target_table: imagenes_procesadas
    process_steps:
      - metadata_extraction
      - face_detection
      - facial_composite_extraction
      - face_matching
      - object_detection
      - ocr
      - location_recognition

  document:
    target_table: documentos_procesados
    process_steps:
      - indexing
      - metadata_extraction
      - ocr
      - semantic_analysis
      - enrichment
      
externalDBs:
  - name: Migracion
    engine: mssql  # Motor de la base de datos (PostgreSQL, MySQL, Oracle, etc.)
    connection:
      host: your_server_address
      port: 1433  # Cambia según el motor de la base de datos (ej. 3306 para MySQL, 5432 para PostgreSQL)
      username: your_username
      password: your_password
      database: your_database_name
      driver: ODBC Driver 17 for SQL Server  # Solo para SQL Server (se puede omitir para otros motores)
    schedule:
      frequency: "1d"  # Frecuencia de sincronización diaria
      time: "02:00"  # Hora de la sincronización diaria
    tables:
      - movimientos_migratorios:
          schema:
            id_movimiento:
              type: SERIAL
              primary_key: true
            nombres:
              type: VARCHAR(255)
            paterno:
              type: VARCHAR(255)
            materno:
              type: VARCHAR(255)
            nacionalidad:
              type: VARCHAR(100)
            documento:
              type: VARCHAR(50)
            numero_doc:
              type: VARCHAR(50)
            fecha_control:
              type: TIMESTAMP
            tipo_mov:
              type: VARCHAR(10)
            pais_movimiento:
              type: VARCHAR(100)
            dependencia:
              type: VARCHAR(255)
          ingestion:
            strategy: replace  # La estrategia puede ser "replace" (reemplazar todos los datos) o "incremental" (solo nuevos registros)
            key: id_movimiento  # Campo clave para detectar duplicados si es "incremental"
            batch_size: 1000  # Tamaño de lotes a procesar en cada sincronización
            filters:  # Filtros opcionales para la consulta
              - field: fecha_control
                condition: ">"  # Condición para filtrar datos recientes
                value: "CURRENT_DATE - INTERVAL '1 day'"

  - name: Compras
    engine: mysql  # Motor de base de datos MySQL
    connection:
      host: your_mysql_server
      port: 3306
      username: mysql_user
      password: mysql_password
      database: compras_db
    schedule:
      frequency: "7d"  # Sincronización semanal
      time: "01:00"  # Hora de la sincronización semanal
    tables:
      - compras_clientes:
          schema:
            id_compra:
              type: SERIAL
              primary_key: true
            id_cliente:
              type: VARCHAR(50)
            producto:
              type: VARCHAR(255)
            cantidad:
              type: INT
            precio:
              type: DECIMAL(10,2)
            fecha_compra:
              type: TIMESTAMP
          ingestion:
            strategy: incremental
            key: id_compra
            batch_size: 500
            filters:
              - field: fecha_compra
                condition: ">"
                value: "CURRENT_DATE - INTERVAL '7 day'"

# Fuentes de archivos
fileSources:
  - name: FTP_Audios
    source_type: ftp
    connection:
      host: ftp.audios.com
      port: 21
      username: ftp_user
      password: ftp_password
    schedule: "0 4 * * *"
    file_format: "audio"
    ingestion:
      file_path: /audios/  # No se especifica target_table, usa la tabla global "audios_procesados" de "processes"

  - name: FTP_Videos
    source_type: ftp
    connection:
      host: ftp.videos.com
      port: 21
      username: ftp_user
      password: ftp_password
    schedule: "0 3 * * *"
    file_format: "video"
    ingestion:
      file_path: /videos/  # Al no especificar target_table, alimenta "videos_procesados" de la definición global

  - name: FTP_Custom_Videos
    source_type: ftp
    connection:
      host: ftp.customvideos.com
      port: 21
      username: ftp_user
      password: ftp_password
    schedule: "0 5 * * *"
    file_format: "video"
    ingestion:
      target_table: custom_videos  # Como especifica target_table, usa esta tabla específica
      file_path: /custom_videos/  # Validación que esta tabla exista en externalDBs

  - name: FTP_Documentos
    source_type: ftp
    connection:
      host: ftp.documentos.com
      port: 21
      username: ftp_user
      password: ftp_password
    schedule: "0 6 * * *"
    file_format: "document"
    ingestion:
      file_path: /documentos/  # Sin target_table, usa "documentos_procesados" de la definición global

# Fuente para deltas de actualización (diferente tratamiento)
  - name: Personas_Delta
    source_type: fileserver  # Puede ser un servidor de archivos o FTP
    connection:
      path: /mnt/deltas/personas/  # Ruta local o montada en el servidor
    schedule: "0 3 * * *"  # Programación diaria a las 3 AM
    file_format: "csv"  # Formato del archivo, que puede ser CSV o personalizado
    ingestion:
      target_table: personas  # Aquí alimentamos directamente la tabla "personas"
      delimiter: "|"  # Separador utilizado en los archivos de texto
      batch_size: 1000  # Tamaño de los lotes para ingesta
      key: id_persona  # Clave primaria para detectar duplicados
      fields_mapping:
        id_persona: 0  # Mapeo de las posiciones de los campos en el archivo
        nombres: 1
        paterno: 2
        materno: 3
        nacionalidad: 4
        documento: 5
        numero_doc: 6
        fecha_nacimiento: 7
      is_delta_update: true  # Indicamos que este es un delta para actualizar una tabla existente
  
  # Fuente para reemplazo total (diferente tratamiento)
  - name: MostWanted_Replacement
    source_type: ftp
    connection:
      host: ftp.mostwanted.com
      port: 21
      username: ftp_user
      password: ftp_password
    schedule: "0 2 1 * *"  # Programación mensual el día 1 de cada mes a las 2 AM
    file_format: "csv"  # Formato del archivo
    ingestion:
      target_table: most_wanted  # Tabla "most_wanted" en la que se reemplazarán los datos
      delimiter: ","  # Separador utilizado en el archivo
      batch_size: 500  # Tamaño de los lotes para ingesta
      fields_mapping:
        id_persona: 0  # Mapeo de las posiciones de los campos en el archivo
        nombres: 1
        alias: 2
        delito: 3
        recompensa: 4
        nacionalidad: 5
      is_replace: true  # Indicamos que este archivo reemplaza todos los datos de la tabla
